heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running Vesta Control
  Panel

parameter_groups:

- label: Server Settings
  parameters:
  - image
  - flavor

- label: Vesta Settings
  parameters:
  - vesta_email_address

- label: rax-dev-params
  parameters:
  - server_hostname
  - kitchen
  - chef_version

parameters:

  server_hostname:
    label: Server Name
    description: Server Name
    type: string
    default: vesta
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment.
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PV)
    constraints:
    - allowed_values:
      - CentOS 6 (PV)
      - CentOS 6 (PVHVM)
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PV)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 2 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  vesta_email_address:
    label: Admin Email
    description: Email address to configure as the administrative user
    type: string
    default: root@localhost

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/vestacp

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

resources:

  vesta_admin_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  vesta_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  vesta_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: vesta_server
    properties:
      username: root
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [vesta_server, accessIPv4] }
      node:
        vesta:
          email: { get_param: vesta_email_address }
          admin_password: { get_attr: [vesta_admin_password, value] }
        run_list: ["recipe[vesta]",
                   "recipe[vesta::firewall]"]

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [vesta_server, accessIPv4] }

  admin_password:
    description: Admin Password
    value: { get_attr: [vesta_admin_password, value] }

  vesta_url:
    description: Vesta URL
    value:
      str_replace:
        template: "https://%server_ip%:8083"
        params:
          "%server_ip%": { get_attr: [vesta_server, accessIPv4] }
